const menu = [
  {
    id: 1,
    title: 'food',
    category: 'breakfast',
    price: 15.99,
    img: './images/item-1.jpeg',
    desc: `Add desc`,
  },
  {
    id: 2,
    title: 'food',
    category: 'lunch',
    price: 13.99,
    img: './images/item-2.jpeg',
    desc: `Add desc.`,
  },
  {
    id: 3,
    title: 'food',
    category: 'shakes',
    price: 6.99,
    img: './images/item-3.jpeg',
    desc: `Add desc.`,
  },
  {
    id: 4,
    title: 'food',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Add desc. `,
  },
  {
    id: 5,
    title: 'food',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `Add desc `,
  },
  {
    id: 6,
    title: 'food',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Add desc`,
  },
  {
    id: 7,
    title: 'food',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `Add desc`,
  },
  {
    id: 8,
    title: 'food',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `Add desc.`,
  },
  {
    id: 9,
    title: 'food',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `Add desc.`,
  },

];
export default menu;
